auto: false
server: false
permalink: /:year/:month/:title.html
pygments: true
base-url: "/"
exclude:
  - readme.md
  - vendor
  - Gemfile
  - Gemfile.lock
category_dir: topics
disqus_shortname: zroger

mini_magick:
  content:
    source: img/photos/original
    destination: img/photos/content
    resize: "640"
  tablet:
    source: img/photos/original
    destination: img/photos/tablet
    resize: "508"
  mobile_landscape:
    source: img/photos/original
    destination: img/photos/mobile_landscape
    resize: "420"
  mobile_portrait:
    source: img/photos/original
    destination: img/photos/mobile_landscape
    resize: "300"
