auto: false
server: false
permalink: /:year/:month/:title.html
pygments: false
base-url: "/"
baseurl: "/"
title: "Roger López"
exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - assets/css/lib
  - bin
  - lib
  - tmp
  - config
  - Assetfile
  - Capfile
category_dir: topics
tag_dir: tags
disqus_shortname: zroger
