baseURL = "https://zroger.com/"
languageCode = "en-us"
title = "Roger López"
theme = "lithium"

[permalinks]
    post = "/:year/:title/"
    page = "/:title/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/zroger"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.png"

